version: '3'

services:
  web:
    build: ./server
    volumes:
      - ./nginx.conf:/etc/nginx/cond.d/nginx.conf
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=lara.localhost
      - NGINX_PORT=80
    working_dir: ${APP_PATH_CONTAINER}

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: test_db
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  redis:
    build: ./cache
    ports:
      - 79:6379

  php:
    build: ./php
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  composer:
    image: composer:2.4
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install